import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ReactNode } from 'react';


const inter = Inter({ subsets: ["latin"] });

type RootLayoutProps = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      
            {children} 
      </body>
       
    </html>
  )
}